from .auth import router as auth_router
from .processes import router as processes_router
from .admin import router as admin_router
from .users import router as users_router
from .deadlines import router as deadlines_router
from .activities import router as activities_router
from .onedrive import router as onedrive_router
from .public import router as public_router
from .stats import router as stats_router
from .ai import router as ai_router
from .documents import router as documents_router
